# HW1: Jupyter Notebook 

In [ ]:
import numpy as np

A = np.array([[0, 1/2, 1/3, 0],
              [1/2, 0, 1/3, 0],
              [1/2, 1/2, 0, 1],
              [0, 0, 1/3, 0]])

eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [ 1.          0.22871355 -0.5        -0.72871355]
Eigenvectors:
 [[ 4.71404521e-01  4.95724430e-01  7.07106781e-01  2.32931941e-01]
 [ 4.71404521e-01  4.95724430e-01 -7.07106781e-01  2.32931941e-01]
 [ 7.07106781e-01 -4.03449957e-01  1.64752789e-16 -8.58619900e-01]
 [ 2.35702260e-01 -5.87998904e-01 -2.20381858e-16  3.92756017e-01]]


In [9]:
eigvecs[0]

array([0.47140452, 0.49572443, 0.70710678, 0.23293194])

In [12]:
v_norm = eigvecs[0]/np.linalg.norm(eigvecs[0])
v_rouned = [round(elem, 4) for elem in v_norm]
print(v_rouned)

[0.4663, 0.4903, 0.6994, 0.2304]
